###############################################################################
#
# Makefile for project 10
#
# Students:
# Arbel Amir, ID 201602109, arbel.amir@mail.huji.ac.il
# Alon Emanuel, ID 205894058, Alon.Derfner@mail.huji.ac.il
#
###############################################################################

all:
	chmod a+x JackCompiler
