###############################################################################
#
# Makefile for a script (e.g. Python), project 6
#
# Students:
# Arbel Amir, ID 201602109, arbel.amir@cs.huji.ac.il
# Alon Emanuel, ID 205894058, Alon.Derfner@cs.huji.ac.il
#
###############################################################################

all:
	chmod a+x Assembler
